blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_index, name='index'),
    path('blog-post/', blog_details_view, name="blog_detail"),
]

employer_portal/urls.py
from django.urls import path, re_path
from .views import *
from .forms import *

app_name = 'employer_portal'

JobPostForms = [
        ('job-details', JobDetailsForm), 
        ('job-requirements', JobRequirementsForm),
        ('compensation-details', CompensationDetailsForm),
        ('application-details', ApplicationDetailsForm),
        ('review-and-publish', JobPostTermsAndConditionsForm),
    ]

InternshipPostForms = [
        ('internship-details', InternshipDetailsForm),
        ('eligibility-criteria', InternshipEligibilityCriteriaForm),
        ('internship-compensation-details', InternshipCompensationDetailsForm),
        ('internship-application-details', InternshipApplicationDetailsForm)
    ]

urlpatterns = [
    path('sign-up/', CompanySignUpWizard.as_view(), name="company_sign_up"),
    path('candidate-profile/<slug:slug>/', candidate_profile, name="candidate_profile"),
    path('dashboard/', dashboard_page, name="dashboard"),
    path('company-profile/', company_profile, name="company_profile"),
    re_path('post-job/(?P<step>.+)', JobPostWizardView.as_view(JobPostForms, url_name='employer_portal:job_post_wizard'), name="job_post_wizard"),
    re_path('post-internship/(?P<step>.+)', InternshipPostWizardView.as_view(InternshipPostForms, url_name='employer_portal:internship_post_wizard'), name="internship_post_wizard"),
    path('job-overview/<slug:slug>', job_overview, name='job_overview'),
    path('manage-jobs/<str:status>/', manage_jobs, name="manage_jobs"),
    path('manage-internships/<str:status>/', manage_internship_listings, name="manage_internships"),
    path('candidate-profiles/', candidate_profiles, name="candidate_profiles"),
    path('job-applications/<slug:slug>/<str:category>/', job_applications, name="job_applications"),
    path('manage-applicant/<slug:job_slug>/<slug:applicant_slug>', manage_applicant, name="manage_applicant"),
    path('schedule-interview/<slug:job_slug>/<slug:applicant_slug>', schedule_interview, name="schedule_interview"),
    path('hiring-decisions/<slug:job_slug>/<slug:applicant_slug>', hiring_decisions, name="hiring_decisions"),
    path('job-interview-schedules/<str:category>/', job_interview_schedules, name="job_interview_schedules"),
    path('job-interview-details/<slug:interview_slug>', job_interview_details, name="job_interview_details"),
    path('candidate-reviews/<slug:candidate_slug>/<str:category>/', candidate_reviews, name="candidate_reviews"),
    path('job-details/<slug:job_slug>/', job_details, name="job_details"),
    path('update-job/<slug:job_slug>', update_job, name="update_job"),
    path('save-candidate/<slug:candidate_slug>', candidate_save_toggle, name="candidate_save_toggle"),
    path('saved-candidates/', saved_candidates, name="saved_candidates"),
    path('application-invite/<slug:candidate_slug>/', send_application_invitation, name="application_invite"),
]

vschools/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
#from machina import urls as machina_urls
import machina
from main.views import *
from employer_portal.views import *
from rest_framework.routers import DefaultRouter

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from django.contrib.sitemaps.views import sitemap
from main.sitemaps import *

sitemaps = {
    'static': StaticSitemap
}


router = DefaultRouter()
router.register(f'jobs', JobDetailsViewSet, basename="job")
router.register(f'job-requirements', JobRequirementsViewSet, basename="job-requirements")
router.register(f'compensation-details', CompensationDetailsViewSet, basename="compensation-details")
router.register(f'application-details', ApplicationDetailsViewSet, basename="application-details")




urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('webpush/', include('webpush.urls')),
    path('employee-portal/', include('employee_portal.urls'), name="employee_portal"),
    path('employer-portal/', include('employer_portal.urls'), name="employer_portal"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

    #DRF Spectacular URL paths
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

    path('main/', include('main.urls'), name="main"),
    path('accounts/', include('allauth.urls'), name="accounts"),
    path('', include('machina.urls'), name="machina"),
    path('blog/', include('blog.urls'), name='blog'),
    path('verify-email/',verify_email_page, name = "verify_email_page"),
    path('join-interview/<slug:interview_slug>', join_interview, name="join_interivew"),
    path('', guest_page, name = "guest"),
    path('about/', about_page, name = "about"),
    path('settings/',settings_page, name = "settings"),
    path('test/', test_page, name = "test"),
    path('pricing/', pricing_page, name="pricing"),
    path('billing/', billing_page, name="billing"),
    path('faq/', FAQ_page),
    path('contact/', contact_page, name="contact"),
    path('verify-email', verify_email, name="verify_email"),
    path('hijack/', include('hijack.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('reset',auth_views.PasswordResetView.as_view(template_name="password-reset/forgot_password.html"), 
        name = "reset_password"),
    path('reset_sent/',
            auth_views.PasswordResetDoneView.as_view(template_name="password-reset/reset_sent.html"), 
            name = "password_reset_done"),
    path('reset/<uidb64>/<token>',
            auth_views.PasswordResetConfirmView.as_view(template_name="password-reset/change_password.html"), 
            name = "password_reset_confirm"), 
    path('reset_complete',
            auth_views.PasswordResetCompleteView.as_view(template_name="password-reset/reset_complete.html"), 
            name = "password_reset_complete")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = 'main.views.handle_404'
handler500 = 'main.views.handle_500'

employer_portal/models.py
from django.db import models
from django.db.models import Count
from django.conf import settings
from django_countries.fields import CountryField
from moneyed import list_all_currencies
from django.utils.text import slugify
from meta.models import ModelMeta
from datetime import timedelta
from django.utils import timezone
import json


class CompanyInformation(models.Model):
    user = models.OneToOneField('main.User', on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255)
    company_website = models.URLField(max_length=255, blank=True, null=True)

    COMPANY_TYPE_CHOICES = [
        ('private','Private'),
        ('public','Public'),
        ('government','Government'),
        ('non_profit','Non-Profit'),
    ]

    company_type = models.CharField(max_length=50, choices=COMPANY_TYPE_CHOICES)

    COMPANY_SIZE_CHOICES = [
        ('small','1 - 50 employees'),
        ('medium', '51 - 200 employees'),
        ('large','201 - 500 employees'),
        ('enterprise', '500+ employees'),
    ]

    company_size = models.CharField(max_length=50, choices=COMPANY_SIZE_CHOICES)
    company_profile_picture = models.ImageField(upload_to="profile_pictures", blank=True, null=True)
    company_email = models.EmailField(max_length=255, blank=True, null=True)
    country = CountryField(blank_label='Select country', blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True, help_text="State/Province/Region")
    city = models.CharField(max_length=255, blank=True, null=True)
    company_linkedin = models.URLField(max_length=255, blank=True, null=True)

    INDUSTRY_CHOICES = [
        ('tech','Technology'),
        ('finance','Finance'),
        ('healthcare','Healthcare'),
        ('education','Education'),
        ('manufacturing','Manufacturing'),
    ]

    industry = models.CharField(max_length=255, choices=INDUSTRY_CHOICES)
    biography = models.TextField(blank=True, null=True)
    company_overview = models.TextField()
    company_vision = models.TextField()
    date_established = models.DateField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    average_rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.company_name



class AccountRepresentative(models.Model):
    user = models.OneToOneField('main.User', on_delete=models.CASCADE)
    company = models.ForeignKey('CompanyInformation', on_delete=models.CASCADE, related_name='representatives')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    linkedin_profile = models.URLField(max_length=255, blank=True, null=True)
    job_title = models.CharField(max_length=255)
    department = models.CharField(max_length=255)
    portfolio_website = models.URLField(max_length=255, blank=True, null=True)
    biography = models.TextField()
    roles_responsibilities = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.job_title})"


class BillingInformation(models.Model):
    user = models.OneToOneField('main.User', on_delete=models.CASCADE, related_name='billing_information')
    company = models.ForeignKey('CompanyInformation', on_delete=models.CASCADE, related_name='billing_information')
    country = CountryField(blank_label='Select country', blank=True, null=True)
    billing_address_1 = models.CharField(max_length=255)
    billing_address_2 = models.CharField(max_length=255, blank=True, null=True)
    billing_email = models.EmailField(max_length=255)
    city = models.CharField(max_length=255)
    state_province_region = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=20)
    full_name_on_card = models.CharField(max_length=255)
    card_number = models.CharField(max_length=16)
    card_expiration = models.CharField(max_length=5)
    cvv_number = models.CharField(max_length=3)

    def __str__(self):
        return f"Billing Information for {self.user.username}"
    

def default_job_expiry_date():
    return timezone.now() + timedelta(days=30)


class JobDetails(models.Model, ModelMeta):
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE, related_name='jobs')
    job_title = models.CharField(max_length=200)
    country = CountryField()
    state_or_region = models.CharField(max_length=200)
    qr_code = models.ImageField(upload_to="job_qr_codes", blank=True, null=True)

    EMPLOYMENT_TYPE_CHOICES = [
        ('full_time','Full-time'),
        ('part_time', 'Part-time'),
        ('contract','Contract'),
        ('apprenticeship','Apprenticeship'),
        ('freelance','Freelance'),
        ('returnship','Returnship'),
    ]

    employment_type = models.CharField(max_length=100, choices=EMPLOYMENT_TYPE_CHOICES)
    company_department = models.CharField(max_length=200)

    INDUSTRY_CHOICES = [
        ('tech','Technology'),
        ('finance','Finance'),
        ('healthcare','Healthcare'),
        ('education','Education'),
        ('manufacturing','Manufacturing'),
    ]

    industry = models.CharField(max_length=200, choices=INDUSTRY_CHOICES)
    job_description = models.TextField()
    video_job_description_url = models.URLField(blank=True, null=True, help_text="Paste a YouTube/Vimeo video URL")
    key_responsibilities = models.JSONField(null=True, help_text='Describe key responsibilities and duties')

    WORK_MODES = [
        ('ONSITE','On-site'),
        ('REMOTE','Remote'),
        ('HYBRID','Hybrid'),
    ]

    work_location_mode = models.CharField(max_length=10, choices=WORK_MODES)

    relocation_assistance = models.BooleanField(default=False, help_text="Does this job offer relocation assistance?")
    relocation_details = models.TextField(blank=True, null=True, help_text="Provide details about the relocation package, if applicable.")

    SENIORITY_LEVELS = [
        ('JR','Junior'),
        ('MD','Mid-level'),
        ('SR','Senior'),
        ('LD','Leadership'),
    ]

    seniority_level = models.CharField(max_length=2, choices=SENIORITY_LEVELS)
    job_description_document = models.FileField(upload_to='job_descriptions/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)

    JOB_STATUS_CHOICES = [
        ('active', 'Active'),
        ('closed', 'Closed'),
        ('expired', 'Expired'),
        ('paused', 'Paused'),
        ('draft', 'Draft'),
        ('scheduled', 'Scheduled')
    ]

    status = models.CharField(max_length=10, choices=JOB_STATUS_CHOICES, default='active')
    publish_date = models.DateTimeField(null=True, blank=True)
    average_rating = models.FloatField(default=0.0)
    expiry_date = models.DateTimeField(default=default_job_expiry_date)
    slug = models.SlugField(unique=True, blank=True, null=True)

    _metadata = {
        "use_title_tag": True,
        "use_schemaorg": True,
        "use_twitter": True,
        "use_og": True,
        "use_facebook": True,
        "site_name": "CareerConnect",
        "title": "get_meta_title",
        "description": "get_meta_description",
        "keywords": "get_meta_keywords",
        "og_type": "article",
        "url": "get_absolute_url",
    }

    _schema = {
        "use_title_tag": True,
        "use_schemaorg": True,
        "use_twitter": True,
        "use_og": True,
        "use_facebook": True,
        "site_name": "CareerConnect",
        "title": "get_meta_title",
        "description": "get_meta_description",
        "keywords": "get_meta_keywords",
        "og_title": "get_meta_title",
        "og_description": "get_meta_description",
        "og_type": "article",
        "twitter_card": "summary_large_image",
        "twitter_title": "get_meta_title",
        "twitter_description": "get_meta_description",
        "schemaorg_title": "get_meta_title",
        "url": "get_absolute_url",
    }

    def get_meta_title(self):
        return f"{self.job_title} at {self.company.company_name} - {self.country}"

    def get_meta_description(self):
        return f"Apply for {self.job_title} at {self.company.company_name} in {self.country}, Industry: {self.industry}, Employment Type: {self.employment_type}"

    def get_meta_keywords(self):
        return [self.job_title, self.company.company_name, self.country, self.industry, self.employment_type, 'jobs', 'hiring']

    def get_absolute_url(self):
        return f"/employee-portal/job-details/{self.slug}/"

    def get_schema_org(self):
        schema_data = {
            "@context": "https://schema.org",
            "@type": "JobPosting",
            "title": self.job_title,
            "hiringOrganization": {
                "@type": "Organization",
                "name": self.company.company_name
            },
            "jobLocation": {
                '@type': 'Place',
                'address': {
                '@type': "PostalAddress",
                "addressLocality": self.country
                }
            }
        }

        return json.dumps(schema_data, indent=4)

    def rating_percentages(self):
        rating_counts = self.job_ratings.values('rating').annotate(count=Count('rating'))

        total_ratings = self.job_ratings.aggregate(total=Count('id'))['total'] or 0

        percentages = {str(i): 0.0 for i in range(5, 0, -1)}

        if total_ratings > 0:
            for rating_data in rating_counts:
                rating_value = str(rating_data['rating'])
                count = rating_data['count']
                percentage = (count / total_ratings) * 100
                percentages[rating_value] = round(percentage, 2)

        return percentages

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.job_title	


class JobRequirements(models.Model):
    job_post = models.OneToOneField(JobDetails, on_delete=models.CASCADE, related_name='job_requirements')

    EDUCATIONAL_LEVEL_CHOICES = [
        ('none', 'No Formal Education'),

templates/employer-portal/post-job/job_submission_complete.html
{% load static %}
{% load compress %}
{% load meta %}

<!DOCTYPE html>
<html lang="en"> 
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% include 'meta/meta.html' %}
        <title>Job Posted Successfully | CareerConnect</title>
        {% compress css %}
        <link rel="stylesheet" href="{% static 'css/flowbite.min.css' %}">
        <link rel="stylesheet" href="{% static 'flags/sprite.css' %}"/>
        {% endcompress %}
        {% compress js %}
        <script src = "{% static 'js/flowbite.min.js' %}" type = "text/javascript"></script>
        {% endcompress %}
    </head>
    <body>
        {% include 'employer-portal/navbar.html' %}

        {% include 'employer-portal/sidebar.html' %}

        <div class="p-4 sm:ml-64">
            <div class="p-4 rounded-lg mt-8">
                <!-- Main Content -->
                <main class="flex-1 flex items-center justify-center">
                    <div class="w-full flex flex-col bg-white rounded-lg py-8">
                        <!-- Icon & Title -->
                        <div class="bg-white flex items-center justify-between">
                            <div class="flex items-center space-x-4 mb-6">
                                <div class="bg-green-100 border border-green-300 text-green-600 p-3 rounded-full">
                                    <svg class="w-8 h-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                                    </svg>
                                </div>
                                <div>
                                    <h2 class="text-2xl font-bold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white">Job Posted Successfully</h2>
                                    <p class="text-base text-gray-500">Your job listing is now live and visible to job seekers.</p>
                                </div>
                            </div>
                            <div class="flex items-center">
                                <a href="{% url 'employer_portal:job_details' job.slug %}" class="py-2.5 px-5 mr-3 flex items-center text-sm font-medium text-center text-blue-600 focus:outline-none bg-white rounded-lg border border-blue-300 hover:bg-blue-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-700 dark:bg-blue-800 dark:text-blue-400 dark:border-blue-600 dark:hover:text-white dark:hover:bg-blue-700">
                                    <svg aria-hidden="true" class="h-4 w-4 mr-2 -ml-0.5" fill="currentColor" viewBox="0 0 20 20"xmlns="http://www.w3.org/2000/svg">
                                        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path>
                                        <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"clip-rule="evenodd"></path>
                                    </svg>
                                    View Details
                                </a>
                                <a href="{% url 'employer_portal:manage_jobs' 'all-jobs' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                    View Your Jobs
                                </a>
                            </div>
                        </div>

                        <div id="alert-border-3" class="flex items-center p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800" role="alert">
                            <svg class="shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                            </svg>
                            <div class="ms-3 text-sm font-semibold">
                                Your job listing is now live and ready to reach the right candidates. You can now track performance from your dashboard, manage applications, and make updates anytime. Let's find your next great hire together.
                            </div>
                            <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700"  data-dismiss-target="#alert-border-3" aria-label="Close">
                                <span class="sr-only">Dismiss</span>
                                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                </svg>
                            </button>
                        </div>

                        <div class="border border-gray-200 p-6">
                            <!-- Job Summary Section -->
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                                <div>
                                    <h3 class="text-sm text-gray-500 dark:text-gray-400 mb-1">Job Title</h3>
                                    <p class="text-base font-medium text-gray-900 dark:text-white">{{ job.job_title }}</p>
                                </div>
                                <div>
                                    <h3 class="text-sm text-gray-500 dark:text-gray-400 mb-1">Company</h3>
                                    <p class="text-base font-medium text-gray-900 dark:text-white">{{ job.company.company_name }}</p>
                                </div>
                                <div>
                                    <h3 class="text-sm text-gray-500 dark:text-gray-400 mb-1">Location</h3>
                                    <p class="text-base font-medium text-gray-900 dark:text-white">{{ job.get_work_location_mode_display }} ({{ job.state_or_region }}, {{ job.country }} <i class="{{ job.country.flag_css }}"></i>)</p>
                                </div>
                                <div>
                                    <h3 class="text-sm text-gray-500 dark:text-gray-400 mb-1">Employment Type</h3>
                                    <p class="text-base font-medium text-gray-900 dark:text-white">{{ job.get_employment_type_display }}</p>
                                </div>
                            </div>

                            <hr class="my-3 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />

                            <!-- Description -->
                            <div class="mb-6">
                                <h3 class="text-sm text-gray-500 dark:text-gray-400 mb-1">Job Description</h3>
                                <p class="text-sm text-gray-800">
                                    {{ job.job_description }}
                                </p>
                            </div>

                            <!-- Action Buttons -->
                            <div class="flex flex-row items-center sm:flex-row gap-4 mt-8">
                                <a href="{% url 'employer_portal:dashboard' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                    Continue to Dashboard
                                    <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
   </body>
</html>